# ============================================================
# MetalLB - Configuration L2 pour LAB
# ============================================================

# -------------------------------
# Pool d'adresses IP utilisables
# -------------------------------
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.122.200-192.168.122.210

---
# -------------------------------
# Annonce L2 (ARP) des IP
# -------------------------------
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lab-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-pool
