# ============================================================
# Ingress NGINX â€“ Customisation cluster LAB
# - IP LoadBalancer fixe (MetalLB)
# - HA (2 replicas)
# ============================================================

# -------------------------------
# Patch Deployment (HA)
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 2

---
# -------------------------------
# Patch Service LoadBalancer
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.122.200
